/**
 * Mutations over a `Workspace` (#163) — pure, immutable, structural
 * sharing, the same contract as `model/graph.ts`: every function returns a
 * new workspace and never touches the one it was given, so the store's
 * snapshot undo is O(changes) rather than O(state), and a throwing mutation
 * leaves state untouched.
 *
 * Ids are generated by callers (`createId()`) and passed in, keeping the
 * mutations themselves deterministic and testable — same rule as graph.ts.
 * This module deliberately does not import graph.ts: the tracker is
 * separate from the project graph, and a one-line id helper is not worth
 * coupling a 1000-line module across that boundary.
 *
 * Removal is conservative by design. `removePerson` / `removeForum` refuse
 * once history references them, because the alternative — cascading — would
 * delete the record of what you agreed with someone the moment they change
 * jobs. Archiving (`Person.archivedAt`) is the non-destructive answer, the
 * same lesson `Resource.availableUntil` encodes on the plan side.
 */

import type {
  Forum,
  Interaction,
  Item,
  ItemState,
  ItemTarget,
  Person,
  Workspace,
} from './types.ts';

/** Thrown when a mutation would break an invariant. */
export class EngagementError extends Error {}

export function createId(): string {
  return crypto.randomUUID();
}

/** ISO datetime "now" — the stamp on created/modified records. */
export function nowIso(): string {
  return new Date().toISOString();
}

/** Today's date as `YYYY-MM-DD`, in local time (what the user calls today). */
export function todayIso(): string {
  const now = new Date();
  const offsetMs = now.getTimezoneOffset() * 60_000;
  return new Date(now.getTime() - offsetMs).toISOString().slice(0, 10);
}

export function emptyWorkspace(): Workspace {
  return { people: [], forums: [], items: {}, interactions: [] };
}

/* --------------------------------- people -------------------------------- */

export interface NewPerson {
  id: string;
  /** May be blank: the roster editor adds an empty row and lets you type
   *  into it, the same way `addResource` does on the plan side. */
  name: string;
  role?: string;
  notes?: string;
}

export function addPerson(workspace: Workspace, person: NewPerson): Workspace {
  if (workspace.people.some((p) => p.id === person.id)) {
    throw new EngagementError(`Duplicate person id: ${person.id}`);
  }
  const record: Person = {
    id: person.id,
    name: person.name.trim(),
    role: person.role ?? '',
    notes: person.notes ?? '',
    away: [],
    archivedAt: null,
    createdAt: nowIso(),
  };
  return { ...workspace, people: [...workspace.people, record] };
}

export function updatePerson(
  workspace: Workspace,
  id: string,
  patch: Partial<Omit<Person, 'id' | 'createdAt'>>,
): Workspace {
  const i = workspace.people.findIndex((p) => p.id === id);
  if (i === -1) throw new EngagementError(`No such person: ${id}`);
  const people = [...workspace.people];
  people[i] = { ...people[i]!, ...patch };
  return { ...workspace, people };
}

/** True when anything in the workspace still points at this person. */
export function personHasHistory(workspace: Workspace, id: string): boolean {
  return (
    workspace.interactions.some((it) => it.participants.includes(id)) ||
    Object.values(workspace.items).some(
      (item) => item.ownerId === id || (item.target.kind === 'person' && item.target.id === id),
    )
  );
}

/**
 * Removes a person with no history. Refuses otherwise — archive them
 * instead (`updatePerson(ws, id, { archivedAt })`), which keeps every
 * interaction and item that records what you agreed with them.
 */
export function removePerson(workspace: Workspace, id: string): Workspace {
  if (!workspace.people.some((p) => p.id === id)) throw new EngagementError(`No such person: ${id}`);
  if (personHasHistory(workspace, id)) {
    throw new EngagementError(
      'That person has items or logged contact — archive them instead of deleting, ' +
        'so the history of what you agreed survives.',
    );
  }
  return {
    ...workspace,
    people: workspace.people.filter((p) => p.id !== id),
    // No history, but they may still sit in a forum's attendee list.
    forums: workspace.forums.map((f) =>
      f.attendees.includes(id) ? { ...f, attendees: f.attendees.filter((a) => a !== id) } : f,
    ),
  };
}

/* --------------------------------- forums -------------------------------- */

export interface NewForum {
  id: string;
  name: string;
  cadenceDays: number;
  anchorDate?: string | null;
  attendees?: string[];
  notes?: string;
}

export function addForum(workspace: Workspace, forum: NewForum): Workspace {
  if (!(forum.cadenceDays > 0)) throw new EngagementError('Cadence must be more than 0 days');
  if (workspace.forums.some((f) => f.id === forum.id)) {
    throw new EngagementError(`Duplicate forum id: ${forum.id}`);
  }
  for (const personId of forum.attendees ?? []) {
    if (!workspace.people.some((p) => p.id === personId)) {
      throw new EngagementError(`No such person: ${personId}`);
    }
  }
  const record: Forum = {
    id: forum.id,
    name: forum.name.trim(),
    cadenceDays: forum.cadenceDays,
    anchorDate: forum.anchorDate ?? null,
    attendees: [...(forum.attendees ?? [])],
    notes: forum.notes ?? '',
    createdAt: nowIso(),
  };
  return { ...workspace, forums: [...workspace.forums, record] };
}

export function updateForum(
  workspace: Workspace,
  id: string,
  patch: Partial<Omit<Forum, 'id' | 'createdAt'>>,
): Workspace {
  const i = workspace.forums.findIndex((f) => f.id === id);
  if (i === -1) throw new EngagementError(`No such forum: ${id}`);
  if (patch.cadenceDays !== undefined && !(patch.cadenceDays > 0)) {
    throw new EngagementError('Cadence must be more than 0 days');
  }
  for (const personId of patch.attendees ?? []) {
    if (!workspace.people.some((p) => p.id === personId)) {
      throw new EngagementError(`No such person: ${personId}`);
    }
  }
  const forums = [...workspace.forums];
  forums[i] = { ...forums[i]!, ...patch };
  return { ...workspace, forums };
}

/** Adds or removes one attendee, leaving the rest of the forum alone. */
export function setForumAttendee(
  workspace: Workspace,
  forumId: string,
  personId: string,
  attending: boolean,
): Workspace {
  const forum = workspace.forums.find((f) => f.id === forumId);
  if (!forum) throw new EngagementError(`No such forum: ${forumId}`);
  const has = forum.attendees.includes(personId);
  if (has === attending) return workspace;
  const attendees = attending
    ? [...forum.attendees, personId]
    : forum.attendees.filter((a) => a !== personId);
  return updateForum(workspace, forumId, { attendees });
}

export function forumHasHistory(workspace: Workspace, id: string): boolean {
  return (
    workspace.interactions.some((it) => it.forumId === id) ||
    Object.values(workspace.items).some(
      (item) => item.target.kind === 'forum' && item.target.id === id,
    )
  );
}

/** Removes a forum nothing references. Refuses once it has items or a
 *  logged history, for the same reason as `removePerson`. */
export function removeForum(workspace: Workspace, id: string): Workspace {
  if (!workspace.forums.some((f) => f.id === id)) throw new EngagementError(`No such forum: ${id}`);
  if (forumHasHistory(workspace, id)) {
    throw new EngagementError(
      'That forum has items or logged meetings — retarget or resolve them first.',
    );
  }
  return { ...workspace, forums: workspace.forums.filter((f) => f.id !== id) };
}

/* --------------------------------- items --------------------------------- */

export interface NewItem {
  id: string;
  title: string;
  target: ItemTarget;
  details?: string;
  ownerId?: string | null;
  state?: ItemState;
  parentId?: string | null;
  dueDate?: string | null;
  recurEveryDays?: number | null;
  link?: Item['link'];
}

function assertTargetExists(workspace: Workspace, target: ItemTarget): void {
  const exists =
    target.kind === 'person'
      ? workspace.people.some((p) => p.id === target.id)
      : workspace.forums.some((f) => f.id === target.id);
  if (!exists) throw new EngagementError(`No such ${target.kind}: ${target.id}`);
}

/** Items with the given parent, in `order`. */
export function childItems(workspace: Workspace, parentId: string | null): Item[] {
  return Object.values(workspace.items)
    .filter((item) => item.parentId === parentId)
    .sort((a, b) => a.order - b.order || a.createdAt.localeCompare(b.createdAt));
}

function nextOrder(workspace: Workspace, parentId: string | null): number {
  const siblings = childItems(workspace, parentId);
  return siblings.length === 0 ? 0 : siblings[siblings.length - 1]!.order + 1;
}

export function addItem(workspace: Workspace, item: NewItem): Workspace {
  if (!item.title.trim()) throw new EngagementError('An item needs a title');
  if (workspace.items[item.id]) throw new EngagementError(`Duplicate item id: ${item.id}`);
  assertTargetExists(workspace, item.target);
  const parentId = item.parentId ?? null;
  if (parentId !== null && !workspace.items[parentId]) {
    throw new EngagementError(`No such item: ${parentId}`);
  }
  if (item.ownerId != null && !workspace.people.some((p) => p.id === item.ownerId)) {
    throw new EngagementError(`No such person: ${item.ownerId}`);
  }
  if (item.recurEveryDays != null && !(item.recurEveryDays > 0)) {
    throw new EngagementError('A recurrence must be more than 0 days');
  }
  const at = nowIso();
  const record: Item = {
    id: item.id,
    title: item.title.trim(),
    details: item.details ?? '',
    target: { ...item.target },
    ownerId: item.ownerId ?? null,
    state: item.state ?? 'to_raise',
    parentId,
    order: nextOrder(workspace, parentId),
    dueDate: item.dueDate ?? null,
    recurEveryDays: item.recurEveryDays ?? null,
    lastRaisedAt: null,
    resolution: '',
    resolvedAt: null,
    link: item.link ?? null,
    createdAt: at,
    modifiedAt: at,
  };
  return { ...workspace, items: { ...workspace.items, [record.id]: record } };
}

/** True when `ancestorId` is `id` or above it in the thread. */
function isAncestorOf(workspace: Workspace, ancestorId: string, id: string): boolean {
  let current: string | null = id;
  const seen = new Set<string>();
  while (current !== null && !seen.has(current)) {
    if (current === ancestorId) return true;
    seen.add(current);
    current = workspace.items[current]?.parentId ?? null;
  }
  return false;
}

export function updateItem(
  workspace: Workspace,
  id: string,
  patch: Partial<Omit<Item, 'id' | 'createdAt' | 'order' | 'lastRaisedAt'>>,
): Workspace {
  const existing = workspace.items[id];
  if (!existing) throw new EngagementError(`No such item: ${id}`);
  if (patch.title !== undefined && !patch.title.trim()) {
    throw new EngagementError('An item needs a title');
  }
  if (patch.target !== undefined) assertTargetExists(workspace, patch.target);
  if (patch.ownerId != null && !workspace.people.some((p) => p.id === patch.ownerId)) {
    throw new EngagementError(`No such person: ${patch.ownerId}`);
  }
  if (patch.recurEveryDays != null && !(patch.recurEveryDays > 0)) {
    throw new EngagementError('A recurrence must be more than 0 days');
  }
  if (patch.parentId !== undefined && patch.parentId !== null) {
    if (!workspace.items[patch.parentId]) throw new EngagementError(`No such item: ${patch.parentId}`);
    if (isAncestorOf(workspace, id, patch.parentId)) {
      throw new EngagementError('An item cannot be threaded under itself');
    }
  }
  const next: Item = { ...existing, ...patch, modifiedAt: nowIso() };
  // Re-home into the new thread's sibling order.
  if (patch.parentId !== undefined && patch.parentId !== existing.parentId) {
    next.order = nextOrder(workspace, next.parentId);
  }
  return { ...workspace, items: { ...workspace.items, [id]: next } };
}

/** Closes an item with a recorded outcome — the issue's "record a
 *  resolution and result". */
export function resolveItem(
  workspace: Workspace,
  id: string,
  resolution: string,
  at: string = nowIso(),
): Workspace {
  if (!workspace.items[id]) throw new EngagementError(`No such item: ${id}`);
  return updateItem(workspace, id, { state: 'resolved', resolution, resolvedAt: at });
}

/** Reopens a resolved/dropped item, clearing its outcome. */
export function reopenItem(workspace: Workspace, id: string): Workspace {
  const item = workspace.items[id];
  if (!item) throw new EngagementError(`No such item: ${id}`);
  return updateItem(workspace, id, {
    state: item.lastRaisedAt === null ? 'to_raise' : 'open',
    resolution: '',
    resolvedAt: null,
  });
}

/** An item and everything threaded under it, deepest last. */
export function itemSubtree(workspace: Workspace, id: string): string[] {
  const out: string[] = [];
  const visit = (current: string) => {
    out.push(current);
    for (const child of childItems(workspace, current)) visit(child.id);
  };
  if (workspace.items[id]) visit(id);
  return out;
}

/**
 * Deletes an item and its thread. Interaction records keep their notes but
 * lose the dangling references, so the log never points at items that no
 * longer exist.
 */
export function removeItem(workspace: Workspace, id: string): Workspace {
  if (!workspace.items[id]) throw new EngagementError(`No such item: ${id}`);
  const doomed = new Set(itemSubtree(workspace, id));
  const items: Record<string, Item> = {};
  for (const [itemId, item] of Object.entries(workspace.items)) {
    if (!doomed.has(itemId)) items[itemId] = item;
  }
  const interactions = workspace.interactions.map((it) => {
    const raised = it.raisedItemIds.filter((x) => !doomed.has(x));
    const created = it.createdItemIds.filter((x) => !doomed.has(x));
    if (raised.length === it.raisedItemIds.length && created.length === it.createdItemIds.length) {
      return it;
    }
    return { ...it, raisedItemIds: raised, createdItemIds: created };
  });
  return { ...workspace, items, interactions };
}

/* ------------------------------ interactions ----------------------------- */

export interface NewInteraction {
  id: string;
  /** ISO date or datetime-local; defaults to today. */
  at?: string;
  forumId?: string | null;
  participants: string[];
  note?: string;
  /** Existing items raised in this contact — stamped `lastRaisedAt`. */
  raisedItemIds?: string[];
  /** Actions agreed in the room, created as part of the same undo step. */
  created?: NewItem[];
}

/**
 * Logs one contact: appends the interaction (newest first), stamps every
 * raised item, and creates any items agreed in the room — all as one
 * mutation, so a meeting is a single undo step rather than a scatter of
 * edits that can half-apply.
 *
 * Raising transitions a one-shot topic from `to_raise` to `open` (it has
 * been said; what's left is whatever action came out of it). A **standing**
 * item (`recurEveryDays`) stays `to_raise` on purpose — it is never "done
 * being raised", it just isn't due again until the recurrence elapses, which
 * `lastRaisedAt` is what gates (see `agenda.ts`).
 */
export function logInteraction(workspace: Workspace, entry: NewInteraction): Workspace {
  if (workspace.interactions.some((it) => it.id === entry.id)) {
    throw new EngagementError(`Duplicate interaction id: ${entry.id}`);
  }
  for (const personId of entry.participants) {
    if (!workspace.people.some((p) => p.id === personId)) {
      throw new EngagementError(`No such person: ${personId}`);
    }
  }
  if (entry.forumId != null && !workspace.forums.some((f) => f.id === entry.forumId)) {
    throw new EngagementError(`No such forum: ${entry.forumId}`);
  }
  const raisedIds = entry.raisedItemIds ?? [];
  for (const itemId of raisedIds) {
    if (!workspace.items[itemId]) throw new EngagementError(`No such item: ${itemId}`);
  }

  const at = entry.at ?? todayIso();
  let next = workspace;

  // Create the agreed actions first, so their ids are real items by the
  // time the interaction record references them.
  for (const item of entry.created ?? []) next = addItem(next, item);

  const items = { ...next.items };
  for (const itemId of raisedIds) {
    const item = items[itemId]!;
    items[itemId] = {
      ...item,
      lastRaisedAt: at,
      state: item.state === 'to_raise' && item.recurEveryDays === null ? 'open' : item.state,
      modifiedAt: nowIso(),
    };
  }

  const record: Interaction = {
    id: entry.id,
    at,
    forumId: entry.forumId ?? null,
    participants: [...entry.participants],
    note: entry.note ?? '',
    raisedItemIds: [...raisedIds],
    createdItemIds: (entry.created ?? []).map((i) => i.id),
  };
  return {
    ...next,
    items,
    interactions: sortInteractions([record, ...next.interactions]),
  };
}

/** Newest first — the order the log reads in. */
export function sortInteractions(interactions: readonly Interaction[]): Interaction[] {
  return [...interactions].sort((a, b) => b.at.localeCompare(a.at) || b.id.localeCompare(a.id));
}

export function removeInteraction(workspace: Workspace, id: string): Workspace {
  if (!workspace.interactions.some((it) => it.id === id)) {
    throw new EngagementError(`No such interaction: ${id}`);
  }
  return { ...workspace, interactions: workspace.interactions.filter((it) => it.id !== id) };
}

/* -------------------------------- lookups -------------------------------- */

export function personById(workspace: Workspace, id: string | null): Person | null {
  if (id === null) return null;
  return workspace.people.find((p) => p.id === id) ?? null;
}

export function forumById(workspace: Workspace, id: string | null): Forum | null {
  if (id === null) return null;
  return workspace.forums.find((f) => f.id === id) ?? null;
}

/** Display name for an item's owner; null owner is me. */
export function ownerLabel(workspace: Workspace, item: Item): string {
  return item.ownerId === null ? 'Me' : (personById(workspace, item.ownerId)?.name ?? 'Unknown');
}

/** Display name for an item's target, person or forum. */
export function targetLabel(workspace: Workspace, item: Item): string {
  const found =
    item.target.kind === 'person'
      ? personById(workspace, item.target.id)?.name
      : forumById(workspace, item.target.id)?.name;
  return found ?? 'Unknown';
}

/** The people on the roster who haven't been archived. */
export function activePeople(workspace: Workspace): Person[] {
  return workspace.people.filter((p) => p.archivedAt === null);
}

/** Items still live — neither resolved nor dropped. */
export function openItems(workspace: Workspace): Item[] {
  return Object.values(workspace.items).filter(
    (item) => item.state === 'to_raise' || item.state === 'open',
  );
}
